name: Build Release APK

on:
  workflow_dispatch:
   inputs:
     release_tag:
       required: false
       type: string

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set Gradle JVM args
        run: echo "org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m" >> gradle.properties

      - name: Clean Project
        run: ./gradlew clean
        
      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Get Version Name
        id: version
        run: |
          # Disesuaikan untuk membaca build.gradle.kts (Kotlin DSL)
          VERSION=$(grep 'versionName' app/build.gradle.kts | head -1 | awk -F'"' '{print $2}')
          if [ -n "${{ github.event.inputs.release_tag }}" ]; then
            echo "name=${{ github.event.inputs.release_tag }}" >> $GITHUB_OUTPUT
          else
            echo "name=$VERSION" >> $GITHUB_OUTPUT
          fi

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk

      - name: Upload to GitHub Release
        id: upload
        if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.name }}
          name: v${{ steps.version.outputs.name }}
          body: |
            ## v${{ steps.version.outputs.name }}
            🔖 Commit: `${{ github.sha }}`
            📋 ${{ github.event.head_commit.message }}
          files: |
            app/build/outputs/apk/release/*.apk
          draft: false
          prerelease: false